version: "3.4"
services:
  sistemdb:
    image: mongo
  sistemyoneticiligiweb:
    image: enginyenice/sistemyoneticiligiweb:latest
  sistemnginx:
    image: enginyenice/sistemyoneticiliginginx:latest

volumes: 
  mongo_volume: