version: "3.4"
services:
  sistemdb:
    image: mongo
  sistemyoneticiligiweb:
    image: : enginyenice/sistemyoneticiligiweb:latest
  sistemnginx:
    build: 
      context: .
      dockerfile: ReverseProxy/Dockerfile

volumes: 
  mongo_volume: