version: "3.8"
services:
  sistemdb:
    container_name: sistemdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db
  sistemyoneticiligiweb:
    container_name: sistemyoneticiligiweb
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=mongodb://sistemdb:27017
    ports: 
      - "5011:80"
    depends_on: 
      - sistemdb
