name: Create Dockerhub Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build Web Project
      working-directory: Project/SistemYoneticiligi.WebUI
      run: docker build . --tag enginyenice/sistemyoneticiligiweb:latest


    - name: Build Web NGINX
      working-directory: Config
      run: docker build . --tag enginyenice/sistemyoneticiliginginx:latest
  

    - name: Dockerhub Login
      env: 
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        RESISTRY_PASSWORD: ${{ secrets.RESISTRY_PASSWORD }}
      run: docker login -u $REGISTRY_USERNAME -p $RESISTRY_PASSWORD
    
    
    - name: Publish  Web Project
      run: docker push enginyenice/sistemyoneticiligiweb:latest


    - name: Publish NGINX
      run: docker push enginyenice/sistemyoneticiliginginx:latest
  
