name: Create Dockerhub Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build to project
      run: docker build . --file Project/SistemYoneticiligi.WebUI/Dockerfile --tag enginyenice/sistemyoneticiligiweb:latest
    - name: Build to nginx
      run: docker build . --file ReverseProxy/Dockerfile --tag enginyenice/sistemyoneticiliginginx:latest
    - name: Dockerhub Login
      env: 
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        RESISTRY_PASSWORD: ${{ secrets.RESISTRY_PASSWORD }}
      run: docker login -u $REGISTRY_USERNAME -p $RESISTRY_PASSWORD
    - name: Publish Projet
      run: docker push enginyenice/sistemyoneticiligiweb:latest
    - name: Publish Nginx
      run: docker push enginyenice/sistemyoneticiliginginx:latest
  
